<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" />
    <PackageReference Include="Reqnroll.NUnit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\BestStories.Api\BestStories.Api.csproj" />
  </ItemGroup>

</Project>
